spring:
  application:
    name: "configserver"
  profiles:
    #active: native
    active: git
  cloud:
    config:
      server:
        #native:
          #search-locations:"classpath:/config"
          #search-locations: "file:///C:/Users/maddu/Desktop/STUDY/PROJECTS/JAVA/MICROSERVICES/config"
        git:
          uri: "https://github.com/eazybytes/eazybytes-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

encrypt:
  key: "RANDOMKEY12345678ABCDEF"

server:
  port: 8801